---

- name: init kubeadm
  command: >
    kubeadm init
    --apiserver-advertise-address={{kube_apiserver_ip}}
    --pod-network-cidr={{kube_pod_network_cidr}}
    --ignore-preflight-errors=all
  register: kubeadm_init

- name: test print kubeadm init output
  debug:
    var: kubeadm_init

#- name: test loop through stdout.lines
#  debug:
#    msg: "{{ item }}"
#  loop: "{{ kubeadm_init.stdoutlines }}"

# the below block to execute only on kubeadm initialization
- name:
#  become: true
#  become_user: "{{kube_non_root_user}}"
  file:
    path: "{{kube_non_root_user_home_dir}}/.kube/config"
    state: directory

- name: copy kubeconfig to user directory
  command: whoami
#  copy:
#    src: /etc/kubernetes/admin.conf
#    dest: "{{kube_non_root_user_home_dir}}/.kube/config"
#    mode: preserve
#    owner: "{{kube_non_root_user}}"
#    group: "{{kube_non_root_user}}"

- name: download pod network manifest
  become: true
  become_user: "{{kube_non_root_user}}"
  get_url:
    url: "{{kube_pod_network_manifest_url}}"
    dest: "{{kube_non_root_user_home_dir}}"

- name: deploy podnetwork
  shell: kubectl apply -f calico.yml
#  when: "{{ kube_pod_network }}" == "calico"

