---

- name: init kubeadm
  changed: false
  command: >
    kubeadm init
    --apiserver-advertise-address={{kube_apiserver_ip}}
    --pod-network-cidr={{kube_pod_network_cidr}}
    --ignore-preflight-errors=all
  register: kubeadm_init

- name: print kubeadm init output
  debug:
    var: kubeadm_init.stdout

- name: create kube directory for non-root user
  become: true
  become_user: "{{kube_non_root_user}}"
  file:
    path: "{{kube_non_root_user_home_dir}}/.kube"
    state: directory
  register: kube_config_user_dir

- name: copy kubeconfig to user directory
  become: true
  copy:
    src: /etc/kubernetes/admin.conf
    dest: kube_config_user_dir.path
    mode: preserve
    owner: "{{kube_non_root_user}}"
    group: "{{kube_non_root_user}}"

- name: download pod network manifest
  become: true
  become_user: "{{kube_non_root_user}}"
  get_url:
    url: "{{kube_pod_network_manifest_url}}"
    dest: "{{kube_non_root_user_home_dir}}"

- name: deploy podnetwork
  shell: kubectl apply -f "{{kube_pod_network}}".yml

