---
- name: add gpg key
  apt_key:
    url: "{{ kube_ubuntu_repo_gpg }}"

- name: add apt repo
  apt_repository:
    repo: "{{ kube_ubuntu_apt_repo }}"
    update_cache: yes

- name: install k8s package
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present

- name: add cgroup driver
  lineinfile:
    path: "{{kubeadm_conf}}"
    insertafter: 'Environment="KUBELET_CONFIG_ARGS=--config=/var/lib/kubelet/config.yaml"'
    line: Environment="cgroup-driver=cgroupfs"
  notify: restart kubelet



