---
- name: add gpg key
  apt_key:
    url: "{{ kube_ubuntu_repo_gpg }}"

- name: add apt repo
  apt_repository:
    repo: "{{ kube_ubuntu_apt_repo }}"
    update_cache: yes

- name: install k8s package
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present


