---

- name: init kubeadm
  command: >
    kubeadm init
    --apiserver-advertise-address={{kube_apiserver_ip}}
    --pod-network-cidr={{kube_pod_network_cidr}}
    --ignore-preflight-errors=all
  register: kubeadm_init

- name: test print kubeadm init output
  debug:
    var: kubeadm_init

#- name: test loop through stdout.lines
#  debug:
#    msg: "{{ item }}"
#  loop: "{{ kubeadm_init.stdoutlines }}"

# the below block to execute only on kubeadm initialization
- name: post kubeadm init steps
  block:
    - name: create .kube directory
      file:
        path: "{{kube_non_root_user_home_dir}}/.kube"
        state: directory

    - name: copy kubeconfig to user directory
      shell: sudo cp -i /etc/kubernetes/admin.conf "{{kube_non_root_user_home_dir}}/.kube/config"

    - name: chown kubeconfig directory
      shell: sudo chown -R "{{kube_non_root_user}}":"{{kube_non_root_user}}" "{{kube_non_root_user_home_dir}}/.kube/config"

    #- name: copy kubeconfig to user directory --> NOT WORKING. GETTING PERMISSION DENIED
    #  copy:
    #    src: /etc/kubernetes/admin.conf
    #    dest: "{{kube_non_root_user_home_dir}}/.kube/config"
    #    mode: 600
    #    owner: "{{kube_non_root_user}}"
    #    group: "{{kube_non_root_user}}"
    #    delegate_to: localhost

    - name: deploy podnetwork
      shell: kubectl apply -f calico.yaml
      register: podnetwork

    - name: run kubectl command
      command: kubectl get pods
      register: kubectl_output

    - name: test kubectl
      debug:
        var: kubectl_output.stdout

  become: true
  become_user: "{{kube_non_root_user}}"

